name: magicchat
description: A new Flutter project created with custom scaffold script.
publish_to: 'none' # Remove this line if publishing to pub.dev

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  # Firebase
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4
  firebase_messaging: ^15.2.4
  google_sign_in: ^6.3.0
  # State management
  flutter_bloc: ^9.1.0
  # for splash screen
  flutter_native_splash: ^2.4.5
  # for adapting screen and font size.
  flutter_screenutil: ^5.9.3
  # An SVG rendering and widget library for Flutter, which allows painting 
  flutter_svg: ^2.0.17
  # Code generator (mainly used with cubit & retrofit)
  freezed_annotation: ^2.4.1
  freezed: ^2.4.6
  # for dependency injection
  get_it: ^8.0.3
  # localization
  intl: ^0.20.2
  easy_localization: ^3.0.7+1
  # Automatically generate code for converting to and from JSON by annotating Dart classes
  json_annotation: ^4.9.0
  json_serializable: ^6.9.0
  # Networking
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.4.2
  retrofit_generator: ^9.1.9
  # easy way to add shimmer effect
  shimmer: ^3.0.0
  # reading and writing simple key-value pairs
  shared_preferences: ^2.5.3
  # provides API to store data in secure storage.
  flutter_secure_storage: ^9.2.4
   #A build system for Dart code generation and modular compilation
  build_runner: ^2.4.15
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  permission_handler: ^12.0.0+1
  http: ^1.3.0
  firebase_app_check: ^0.3.2+5
  # for showing charts
  fl_chart: ^1.0.0
  collection: ^1.18.0
  # smooth page indicator for onboarding screen
  smooth_page_indicator: ^1.2.1
  # for showing emojis in text field
  emoji_picker_flutter: ^4.3.0
  screenshot: ^3.0.0
  rxdart: ^0.28.0
  flutter_launcher_icons: ^0.14.3
  flutter_en_json_extractor: ^0.0.4
  # Displaying and scheduling local notifications for Flutter applications
  flutter_local_notifications: ^19.2.1
  # for notifications
  googleapis_auth: ^2.0.0
  image_cropper: ^9.1.0
  internet_connection_checker_plus: ^2.7.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  path_provider: ^2.0.15
  lottie: ^3.3.1
  dropdown_button2: ^2.3.9
  audioplayers: ^6.5.0
  url_launcher: ^6.3.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/app_icon.png"

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/lang/en.json
    - assets/lang/ar.json
    - assets/lottie/
    - assets/sounds/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package